version: "3.8"

services:
  query-subgraph:
    build:
      context: ./subgraphs/query-subgraph
    image: graphql-apollo-router-poc-query-subgraph:latest
    ports:
      - "4001:4001"
    working_dir: /app
    command: ["node", "index.js"]

  mutation-subgraph:
    build:
      context: ./subgraphs/mutation-subgraph
    image: graphql-apollo-router-poc-mutation-subgraph:latest
    ports:
      - "4002:4002"
    working_dir: /app
    command: ["node", "index.js"]

  router:
    build:
      context: ./router
    image: graphql-apollo-router-poc-router:latest
    ports:
      - "4000:4000"
    command: ["--supergraph", "/supergraph.graphql"]
