apiVersion: apps/v1
kind: Deployment
metadata:
  name: mutation-subgraph
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mutation-subgraph
  template:
    metadata:
      labels:
        app: mutation-subgraph
    spec:
      containers:
        - name: mutation-subgraph
          image: 851725443575.dkr.ecr.us-east-1.amazonaws.com/mutation-subgraph:latest
          ports:
            - containerPort: 4002
---
apiVersion: v1
kind: Service
metadata:
  name: mutation-subgraph
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 4002
  selector:
    app: mutation-subgraph
