apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-subgraph
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query-subgraph
  template:
    metadata:
      labels:
        app: query-subgraph
    spec:
      containers:
        - name: query-subgraph
          image: 851725443575.dkr.ecr.us-east-1.amazonaws.com/query-subgraph:latest
          ports:
            - containerPort: 4001
---
apiVersion: v1
kind: Service
metadata:
  name: query-subgraph
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 4001
  selector:
    app: query-subgraph
