apiVersion: apps/v1
kind: Deployment
metadata:
  name: apollo-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apollo-router
  template:
    metadata:
      labels:
        app: apollo-router
    spec:
      containers:
        - name: apollo-router
          image: 851725443575.dkr.ecr.us-east-1.amazonaws.com/apollo-router:latest
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: apollo-router
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 4000
  selector:
    app: apollo-router
